version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - db_data:/app/data
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - RP_ID=${RP_ID}
      - ORIGIN=${ORIGIN}
      - DB_PATH=/app/data/database.sqlite
    restart: unless-stopped

volumes:
  db_data:
    driver: local